# Basic Tensor Operations
TensorFlow v2
- Author: Aymeric Damien
- Project: https://github.com/aymericdamien/TensorFlow-Examples/

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

In [3]:
# Tensors also support python operators (+, *, ...)
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print(f'div = {round(div.numpy(), 3)}')

add = 5
sub = -1
mul = 6
div = 0.667


In [4]:
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

print(f'mean = {mean.numpy()}')
print(f'sum = {sum.numpy()}')

mean = 3
sum = 10


In [5]:
# 행렬 곱(Matrix multiplications)
matrix1 = tf.constant([[1., 2.],
                       [3., 4.]])
matrix2 = tf.constant([[5., 6.],
                       [7., 8.]])
# Display Tensor
product = tf.matmul(matrix1, matrix2)
product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [6]:
product.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)