[TensorFlow](https://www.youtube.com/watch?v=B961QM47g64)

In [4]:
import numpy as np
import tensorflow as tf

In [3]:
def sigmoid(x):
    return (1 / (1 + np.exp(-x)))

def Neuron(x, W, bias=0):
    z = x * W + bias
    return sigmoid(z)

In [7]:
x = tf.random.normal((2, 1), 0, 1)
W = tf.random.normal((2, 1), 0, 1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x, W))

x.shape: (2, 1)
W.shape: (2, 1)
tf.Tensor(
[[ 0.5340308 ]
 [-0.61117804]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[-1.0456431]
 [ 1.2316655]], shape=(2, 1), dtype=float32)
[[0.36391643]
 [0.3202187 ]]


In [8]:
x = 1
y = 0
W = tf.random.normal([1], 0, 1)
print(Neuron(x, W))
print('y:', y)

[0.37085637]
y: 0


In [9]:
for i in range(1000):
    output = Neuron(x, W)
    error = y - output
    W = W + x * 0.1 * error

    if i % 100 == 99:
        print(f"{i+1}\t{error}\t{output}")

100	[-0.09172301]	[0.09172301]
200	[-0.04933936]	[0.04933936]
300	[-0.03346449]	[0.03346449]
400	[-0.02524849]	[0.02524849]
500	[-0.02024639]	[0.02024639]
600	[-0.01688743]	[0.01688743]
700	[-0.01447869]	[0.01447869]
800	[-0.01266812]	[0.01266812]
900	[-0.01125812]	[0.01125812]
1000	[-0.01012931]	[0.01012931]


In [12]:
def Neuron2(x, W, bias=0):
    z = tf.matmul(x, W, transpose_b=True) + bias
    return sigmoid(z)

In [13]:
x = tf.random.normal((1, 3), 0, 1)
y = tf.ones(1)
W = tf.random.normal((1, 3), 0, 1)

print(Neuron2(x, W))
print("y:", y)

[[0.30701903]]
y: tf.Tensor([1.], shape=(1,), dtype=float32)


In [14]:
for i in range(1000):
    output = Neuron2(x, W)
    error = y - output
    W = W + x * 0.1 * error

    if i % 100 == 99:
        print(f'{i+1}\t{error}\t{output}')

100	[[0.01643872]]	[[0.9835613]]
200	[[0.00806099]]	[[0.991939]]
300	[[0.00533366]]	[[0.99466634]]
400	[[0.00398403]]	[[0.99601597]]
500	[[0.00317895]]	[[0.99682105]]
600	[[0.00264442]]	[[0.9973556]]
700	[[0.00226367]]	[[0.99773633]]
800	[[0.00197864]]	[[0.99802136]]
900	[[0.00175738]]	[[0.9982426]]
1000	[[0.0015806]]	[[0.9984194]]


In [15]:
x = tf.random.normal((1, 3), 0, 1)
weights = tf.random.normal((1, 3), 0, 1)
bias = tf.zeros((1, 1))

y = tf.ones((1,))

print(f'x\t: {x}\nweights\t: {weights}\nbias\t: {bias}')

x	: [[ 0.11911952  0.591529   -0.4192188 ]]
weights	: [[-0.9560744   0.04003976  0.55955625]]
bias	: [[0.]]


In [16]:
for i in range(1000):
    output = Neuron2(x, weights, bias=bias)
    error = y - output
    weights = weights + x * 0.1 * error
    bias = bias + 1 * 0.1 * error

    if i % 100 == 99:
        print(f'{i+1}\t{error}\t{output}')

100	[[0.07030433]]	[[0.92969567]]
200	[[0.03456688]]	[[0.9654331]]
300	[[0.02276337]]	[[0.9772366]]
400	[[0.01693487]]	[[0.9830651]]
500	[[0.01347101]]	[[0.986529]]
600	[[0.01117849]]	[[0.9888215]]
700	[[0.00955027]]	[[0.9904497]]
800	[[0.0083347]]	[[0.9916653]]
900	[[0.00739276]]	[[0.99260724]]
1000	[[0.00664157]]	[[0.99335843]]
